Update to Google Cloud 151
riceo/step-kubectl pull request #2
Opened 2017-04-19 21:21 UTC by omarkj

This updates the Google SDK to 151 which includes kubectl 1.6.0.

When doing this I hit a Wercker bug (or feature?) where a step has a maximum size of 50MB. How I got around this is explained in commit 3dc01e658854f1b59975e6ac6650889ea7cc6675.

I can rebase etc. as needed, just let me know.

2017-05-08 13:32 UTC, riceo requested changes
Thanks for the contribution! Does the addition of the upx steps affect build time much?

2017-05-08 13:32 UTC, riceo commented on ewok.yml
>                  echo "Installing version $KUBERNETES_VERSION of kubernetes and ${GCLOUD_VERSION} of the Google Cloud SDK"
$KUBERNETES_VERSION has been removed. Feel free to remove the message rather than add the variable back.

2017-05-08 15:15 UTC, omarkj commented
UPX slows down the building of the step quite a lot (it can take a minute or so to compress the binary) but it does not noticeably slow down usage of the step.

2017-05-08 16:15 UTC, riceo commented
Ah ok. Thanks again for contributing!

2017-05-08 16:15 UTC, merged

2017-05-25 01:04 UTC, chrisfelesoid commented
When will it be published?

2017-05-25 21:50 UTC, omarkj commented
Hi chrisfelesoid, 

Until Riceo publishes the official kubectl step I've been using [this updated copy of it](https://app.wercker.com/applications/58f7b74c53c3050100cc7a17/tab/details/).

2017-05-26 01:20 UTC, chrisfelesoid commented
@omarkj 
Thanks! It works!!